version: '3.8'
services:
  app:
    build: .
    container_name: once_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure

  db:
    image: mysql:8.0
    container_name: once_mysql
    environment:
      MYSQL_DATABASE: prodMain
      MYSQL_USER: dev
      MYSQL_PASSWORD: Ag111^@ergnuio
      MYSQL_ROOT_PASSWORD: nuhayserver
    ports:
      - "3305:3306"
    volumes:
      - db_data:/var/lib/mysql
  tg:
    build: ./TgBot
    container_name: once_tg
    depends_on:
      - db
    restart: always
  nginx:
    image: nginx
    container_name: once_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: on-failure
  grafana:
    image: grafana/grafana
    container_name: once_grafana
    ports:
      - "3000:3000"
    depends_on:
      - db
      - app
    restart: on-failure

volumes:
  db_data:






